---
title: "Can constraint closure provide a generalized understanding of community dynamics in ecosystems?"
author: "Steven L. Peck and Andrew Heiss"
date: "Last run: `r format(Sys.time(), '%B %e, %Y')`"
---

## Abstract

Since the inception of the discipline, understanding causal complexity in ecological communities has been a challenge. Here we draw insights from recent work on constraint closure that suggests ways of grappling with ecological complexity that yield generalizable theoretical insights. Using a set of evolutionary constraints on species flow through ecological communities, which include: selection, species drift, dispersal, and speciation, combined with multispecies interactions such as mutualistic interactions, and abiotic constraints, we demonstrate how constraint closure allows communities to emerge as semi-autonomous structures. Here we develop an agent-based model to explore how evolutionary constraints provide stability to ecological communities. The model is written in Netlogo, an agent based-modeling system, with advanced tools for manipulating spatially structured models and tools for tracking pattern formation. We articulate ways that ecological pattern formation, viewed through the lens of constraint closure, informs questions about stability and turnover in community ecology. The role of the chosen constraints was clear from the simulation results. It took the shape of both inducing stability and creating conditions for a more dynamic community with increases in species turnover through time. Key ecological and evolutionary variables showed overall stability in the landscape structure when plotted against the number of constraints, suggesting that these evolutionary forces act as constraints to the flow of species in such a way that constraint closure is achieved effecting semi-autonomy.
